name: CI

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm run lint
        env:
          CI: true